// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x1BtAZcYDoHQadMwGq1GLr
// Component: Smd1VB5lX-Cx

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: aFU8osBh9vPy/component
import SubpageHeader from "../../SubpageHeader"; // plasmic-import: lpLjDJwsHcxv/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x1BtAZcYDoHQadMwGq1GLr/projectcss
import sty from "./PlasmicLeInsights.module.css"; // plasmic-import: Smd1VB5lX-Cx/css

createPlasmicElementProxy;

export type PlasmicLeInsights__VariantMembers = {};
export type PlasmicLeInsights__VariantsArgs = {};
type VariantPropType = keyof PlasmicLeInsights__VariantsArgs;
export const PlasmicLeInsights__VariantProps = new Array<VariantPropType>();

export type PlasmicLeInsights__ArgsType = {};
type ArgPropType = keyof PlasmicLeInsights__ArgsType;
export const PlasmicLeInsights__ArgProps = new Array<ArgPropType>();

export type PlasmicLeInsights__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  subpageHeader?: Flex__<typeof SubpageHeader>;
};

export interface DefaultLeInsightsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLeInsights__RenderFunc(props: {
  variants: PlasmicLeInsights__VariantsArgs;
  args: PlasmicLeInsights__ArgsType;
  overrides: PlasmicLeInsights__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $translator = usePlasmicTranslator?.();
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <section
                    className={classNames(projectcss.all, sty.section__jPaGl)}
                  >
                    <SubpageHeader
                      data-plasmic-name={"subpageHeader"}
                      data-plasmic-override={overrides.subpageHeader}
                      className={classNames(
                        "__wab_instance",
                        sty.subpageHeader
                      )}
                      slot={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tZbCd
                          )}
                        >
                          <Trans__>
                            {
                              <React.Fragment>
                                <React.Fragment>
                                  {
                                    "Understanding and learning from lived experience is essential to navigating the unprecedented compounding crises of mental health and climate change. "
                                  }
                                </React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ fontWeight: 700 }}
                                >
                                  {
                                    "Browse our library of  lived experience insights"
                                  }
                                </span>
                                <React.Fragment>
                                  {
                                    " shared by people across the globe, providing invaluable insights into impacts and solutions.  "
                                  }
                                </React.Fragment>
                              </React.Fragment>
                            }
                          </Trans__>
                        </div>
                      }
                      slot2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__h95Wo)}
                          displayHeight={"216px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"274px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/hubLivedExperiencespng.png",
                            fullWidth: 6097,
                            fullHeight: 5860,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xbYih
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>
                                {"Lived Experience "}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                              >
                                {"Insights"}
                              </span>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                    </SubpageHeader>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__rb23L)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wVqs
                      )}
                    >
                      <Trans__>{"This is a title of section"}</Trans__>
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__fo4WW)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/dev_goh/images/screenshot20240207At34011Pmpng.png",
                        fullWidth: 1674,
                        fullHeight: 622,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__i1G1J
                      )}
                    >
                      <Trans__>{"This is a title of section"}</Trans__>
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__kw6Dj)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/dev_goh/images/screenshot20240207At34011Pmpng.png",
                        fullWidth: 1674,
                        fullHeight: 622,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nLvRw
                      )}
                    >
                      <Trans__>{"This is a title of section"}</Trans__>
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___7Jy8E)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/dev_goh/images/screenshot20240207At34011Pmpng.png",
                        fullWidth: 1674,
                        fullHeight: 622,
                        aspectRatio: undefined
                      }}
                    />
                  </section>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "subpageHeader"],
  pageLayout: ["pageLayout", "subpageHeader"],
  subpageHeader: ["subpageHeader"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  subpageHeader: typeof SubpageHeader;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLeInsights__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLeInsights__VariantsArgs;
    args?: PlasmicLeInsights__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLeInsights__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLeInsights__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLeInsights__ArgProps,
          internalVariantPropNames: PlasmicLeInsights__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLeInsights__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLeInsights";
  } else {
    func.displayName = `PlasmicLeInsights.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"x1BtAZcYDoHQadMwGq1GLr"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={false}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

export const PlasmicLeInsights = Object.assign(
  // Top-level PlasmicLeInsights renders the root element
  withPlasmicPageGuard(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    subpageHeader: makeNodeComponent("subpageHeader"),

    // Metadata about props expected for PlasmicLeInsights
    internalVariantProps: PlasmicLeInsights__VariantProps,
    internalArgProps: PlasmicLeInsights__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLeInsights;
/* prettier-ignore-end */
