// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x1BtAZcYDoHQadMwGq1GLr
// Component: lpLjDJwsHcxv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x1BtAZcYDoHQadMwGq1GLr/projectcss
import sty from "./PlasmicSubpageHeader.module.css"; // plasmic-import: lpLjDJwsHcxv/css

createPlasmicElementProxy;

export type PlasmicSubpageHeader__VariantMembers = {};
export type PlasmicSubpageHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicSubpageHeader__VariantsArgs;
export const PlasmicSubpageHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicSubpageHeader__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicSubpageHeader__ArgsType;
export const PlasmicSubpageHeader__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2"
);

export type PlasmicSubpageHeader__OverridesType = {
  header?: Flex__<"section">;
  columns?: Flex__<"div">;
};

export interface DefaultSubpageHeaderProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSubpageHeader__RenderFunc(props: {
  variants: PlasmicSubpageHeader__VariantsArgs;
  args: PlasmicSubpageHeader__ArgsType;
  overrides: PlasmicSubpageHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $translator = usePlasmicTranslator?.();
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <section
      data-plasmic-name={"header"}
      data-plasmic-override={overrides.header}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.header
      )}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(projectcss.all, sty.columns)}
      >
        <div className={classNames(projectcss.all, sty.column__ac39U)}>
          <div className={classNames(projectcss.all, sty.freeBox___9Hjt2)}>
            {renderPlasmicSlot({
              defaultContents: <Trans__>{"Research & Action"}</Trans__>,
              value: args.children,
              className: classNames(sty.slotTargetChildren)
            })}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__tUHy)}>
            {renderPlasmicSlot({
              defaultContents: (
                <Trans__>
                  {
                    "Explore our rich repository of co-created agendas, reports, case studies and tools, all designed to support collaboration between disciplines and provide focus for the emerging field of climate change and mental health . \n"
                  }
                </Trans__>
              ),
              value: args.slot,
              className: classNames(sty.slotTargetSlot)
            })}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.column__cBij)}>
          {renderPlasmicSlot({
            defaultContents: (
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___42Mb5)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"274px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dev_goh/images/peoplepng.png",
                  fullWidth: 1370,
                  fullHeight: 981,
                  aspectRatio: undefined
                }}
              />
            ),

            value: args.slot2
          })}
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header: ["header", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header: "section";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSubpageHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSubpageHeader__VariantsArgs;
    args?: PlasmicSubpageHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSubpageHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSubpageHeader__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSubpageHeader__ArgProps,
          internalVariantPropNames: PlasmicSubpageHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSubpageHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header") {
    func.displayName = "PlasmicSubpageHeader";
  } else {
    func.displayName = `PlasmicSubpageHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicSubpageHeader = Object.assign(
  // Top-level PlasmicSubpageHeader renders the root element
  makeNodeComponent("header"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicSubpageHeader
    internalVariantProps: PlasmicSubpageHeader__VariantProps,
    internalArgProps: PlasmicSubpageHeader__ArgProps
  }
);

export default PlasmicSubpageHeader;
/* prettier-ignore-end */
