// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x1BtAZcYDoHQadMwGq1GLr
// Component: _X-IBH52BLjl

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: aFU8osBh9vPy/component
import SubpageHeader from "../../SubpageHeader"; // plasmic-import: lpLjDJwsHcxv/component
import AgendaCard from "../../AgendaCard"; // plasmic-import: F27DgGdVuq-P/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import { useScreenVariants as useScreenVariantsxIrZdHvFaFjh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: xIrZDHvFaFjh/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x1BtAZcYDoHQadMwGq1GLr/projectcss
import sty from "./PlasmicResearchAction.module.css"; // plasmic-import: _X-IBH52BLjl/css

createPlasmicElementProxy;

export type PlasmicResearchAction__VariantMembers = {};
export type PlasmicResearchAction__VariantsArgs = {};
type VariantPropType = keyof PlasmicResearchAction__VariantsArgs;
export const PlasmicResearchAction__VariantProps = new Array<VariantPropType>();

export type PlasmicResearchAction__ArgsType = {};
type ArgPropType = keyof PlasmicResearchAction__ArgsType;
export const PlasmicResearchAction__ArgProps = new Array<ArgPropType>();

export type PlasmicResearchAction__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  subpageHeader?: Flex__<typeof SubpageHeader>;
  agendas?: Flex__<"section">;
  caseStudies?: Flex__<"section">;
  toolkits?: Flex__<"section">;
  caseStudies2?: Flex__<"section">;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultResearchActionProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicResearchAction__RenderFunc(props: {
  variants: PlasmicResearchAction__VariantsArgs;
  args: PlasmicResearchAction__ArgsType;
  overrides: PlasmicResearchAction__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $translator = usePlasmicTranslator?.();
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxIrZdHvFaFjh()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <SubpageHeader
                    data-plasmic-name={"subpageHeader"}
                    data-plasmic-override={overrides.subpageHeader}
                    className={classNames("__wab_instance", sty.subpageHeader)}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jwos6
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>
                                {"Explore our rich "}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {
                                  "repository of research agendas, reports, case studies and tools,"
                                }
                              </span>
                              <React.Fragment>
                                {
                                  " all designed to support collaboration between disciplines and sectors and accelerate and align the growing field of climate change and mental health research. "
                                }
                              </React.Fragment>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                    }
                    slot2={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__pgMZl)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "240px"
                            : "auto"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "292px"
                            : "274px"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/dev_goh/images/hubResearchActionV2Png.png",
                          fullWidth: 5860,
                          fullHeight: 6097,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e3M3V
                      )}
                    >
                      <Trans__>
                        {
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                            >
                              {"Catalysing"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-PY84l1C8mrNw)" }}
                            >
                              {" climate change and mental health "}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                            >
                              {"research"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-PY84l1C8mrNw)" }}
                            >
                              {" "}
                            </span>
                          </React.Fragment>
                        }
                      </Trans__>
                    </div>
                  </SubpageHeader>
                  <section
                    data-plasmic-name={"agendas"}
                    data-plasmic-override={overrides.agendas}
                    className={classNames(projectcss.all, sty.agendas)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xm25R)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iTykt
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>
                                {"Research & Action "}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                              >
                                {"Agendas"}
                              </span>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tzESo
                        )}
                      >
                        <Trans__>
                          {
                            "The Connecting Climate Minds Research and Action Agendas set out research priorities to understand and address the needs of people experiencing and responding to the mental health burden of the climate crisis, and priorities to enable this research and translate evidence into action in policy and practice. \n\nThese agendas aim to support those who are already responding to climate-related mental health challenges by building a more connected and collaborative climate change and mental health field. They also aim to empower experts across disciplines and sectors to join and make progress in this area by identifying clear priorities and fostering a more inclusive and transdisciplinary field. "
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__qBJo
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__mn9C6
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__wAyS5
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__ytw5)}
                                displayHeight={"304px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/globalAgendapng.png",
                                  fullWidth: 3840,
                                  fullHeight: 2160,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={<Trans__>{"Global Agenda"}</Trans__>}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__amtTs
                              )}
                            >
                              <Trans__>
                                {
                                  "The global research and action agenda for climate change and mental health aims to help focus the efforts of research, funding, policy, and practice communities around the world working toward a future where no one is held back by climate-related mental health challenges."
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__kSDh1
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard___3Hk7C
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__u58IS)}
                                displayHeight={"303px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/regionalAgendaspng.png",
                                  fullWidth: 3840,
                                  fullHeight: 2160,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={<Trans__>{"Regional Agendas"}</Trans__>}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oS9
                              )}
                            >
                              <Trans__>
                                {
                                  "Regional agendas set out priorities for research and priority actions to enact and translate that research in seven global regions (in line with the Sustainable Development Goal regional groupings).\n"
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__rpWse
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__cCiIg
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__otdm6
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__iDw3O)}
                                displayHeight={"204px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/ypAgendapng2.png",
                                  fullWidth: 3840,
                                  fullHeight: 2160,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={<Trans__>{"Youth Agenda"}</Trans__>}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__umzx7
                              )}
                            >
                              <Trans__>
                                {
                                  "This agenda sets out priorities for research that can support youth mental health in the context of climate change, and priority actions to enact and translate that research, informed by insights shared by young people around the world.\n\n"
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__a5H4M
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__d1FN
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__bsFsK)}
                                displayHeight={"207px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/indigenousAgendapng2.png",
                                  fullWidth: 3840,
                                  fullHeight: 2160,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={
                              <Trans__>
                                {"Indigenous Nations and Peoples Agenda"}
                              </Trans__>
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fvywu
                              )}
                            >
                              <Trans__>
                                {
                                  "This agenda sets out priorities for research that can inform action to meet the needs of  Indigenous People experiencing and responding to the mental health impacts of climate change, informed by insights shared by Indigenous People and communities around the world. "
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__wvBpg
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__teqc6
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__btxim)}
                                displayHeight={"208px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/farmerAgendapng2.png",
                                  fullWidth: 3840,
                                  fullHeight: 2160,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={
                              <Trans__>
                                {"Small Farmer and Fisher People Agenda"}
                              </Trans__>
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uopKn
                              )}
                            >
                              <Trans__>
                                {
                                  "This agenda sets out priorities for research that can inform action to meet the needs of  small farmers and fisher people experiencing and responding to the mental health impacts of climate change, informed by insights shared by small farmers and fisher people  around the world. "
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3Ga7C
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hbxMk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__edZrf
                            )}
                          >
                            <Trans__>
                              {"How were the agendas developed?"}
                            </Trans__>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__deXzy
                            )}
                          >
                            <Trans__>
                              {
                                "We convened experts across disciplines, sectors and countries in over 20 virtual and in person dialogues. Our impact reports demonstrate and celebrate the diversity of activities and collaboration fostered through Connecting Climate Minds that informed the agendas.\n "
                              }
                            </Trans__>
                          </div>
                        </div>
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__s3Uua)}
                          displayHeight={"363px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"641px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/inforgraphicpng.png",
                            fullWidth: 2905,
                            fullHeight: 1599,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </section>
                  <section
                    data-plasmic-name={"caseStudies"}
                    data-plasmic-override={overrides.caseStudies}
                    className={classNames(projectcss.all, sty.caseStudies)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nMgz3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rwLse
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-PY84l1C8mrNw)" }}
                              >
                                {"Successful "}
                              </span>
                              <React.Fragment>{""}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                              >
                                {"case studies"}
                              </span>
                              <React.Fragment>{""}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-PY84l1C8mrNw)" }}
                              >
                                {" across the globe"}
                              </span>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v17Ty
                        )}
                      >
                        <Trans__>
                          {
                            "Discover our interactive map, which provides a broad and inclusive overview of successful case studies in the fields of mental health and climate change, highlighting innovative research and projects from various corners of the world."
                          }
                        </Trans__>
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__bN0XH)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/dev_goh/images/caseStudyMapjpg.jpg",
                          fullWidth: 3840,
                          fullHeight: 2160,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </section>
                  <section
                    data-plasmic-name={"toolkits"}
                    data-plasmic-override={overrides.toolkits}
                    className={classNames(projectcss.all, sty.toolkits)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__e95Eu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5DBRr
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>
                                {"Community created "}
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                              >
                                {"toolkits"}
                              </span>
                              <React.Fragment> </React.Fragment>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aGwZq
                        )}
                      >
                        <Trans__>
                          {
                            "Our toolkits offer comprehensive guidance on conducting and translating climate change and mental health research. Each toolkit has been carefully crafted by a diverse team to provide practical advice, strategies, and resources, helping you to navigate these complex fields with greater clarity and effectiveness. "
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__pDcN
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__mq1Gb
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__vJrvS
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__bkjxh)}
                                displayHeight={"171px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/ccc4V2Png.png",
                                  fullWidth: 6445,
                                  fullHeight: 5564,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__tfdwd
                                )}
                              >
                                <Trans__>
                                  {
                                    <React.Fragment>
                                      <React.Fragment>
                                        {
                                          "Deepening Research & Practice: A Lived Experience Engagement Toolkit "
                                        }
                                      </React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{
                                          color: "#205596",
                                          fontStyle: "italic"
                                        }}
                                      >
                                        {"by Connecting Climate Minds"}
                                      </span>
                                    </React.Fragment>
                                  }
                                </Trans__>
                              </div>
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tUoba
                              )}
                            >
                              <Trans__>
                                {
                                  "Drawing upon the collective wisdom of experts and individuals with firsthand experience and lessons from international collaborations, the toolkit offers practical guidance on navigating the complexities of lived experience engagement in the context of climate change and mental health research and practice."
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__weHyj
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__rhIq
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__uMuqX)}
                                displayHeight={"171px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/ccc1V3Png.png",
                                  fullWidth: 7346,
                                  fullHeight: 5624,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={
                              <Trans__>
                                {
                                  "Toolkit for decision-makers taking action to support mental health in the climate crisis"
                                }
                              </Trans__>
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___6M7Aw
                              )}
                            >
                              <Trans__>
                                {
                                  "This toolkit aims to provide policymakers, decision-makers, NGOs, and practitioners with a concise overview of the climate-mental health nexus, its importance, key messages, and practical ways to engage.\n"
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__xgWeD
                          )}
                        >
                          <AgendaCard
                            className={classNames(
                              "__wab_instance",
                              sty.agendaCard__oUwpL
                            )}
                            slot={
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__tmhXr)}
                                displayHeight={"171px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"100%"}
                                loading={"lazy"}
                                src={{
                                  src: "/plasmic/dev_goh/images/ccc5V2Png.png",
                                  fullWidth: 6526,
                                  fullHeight: 5953,
                                  aspectRatio: undefined
                                }}
                              />
                            }
                            title={
                              <Trans__>
                                {"101 for researchers in the MM&CC field"}
                              </Trans__>
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5URG
                              )}
                            >
                              <Trans__>
                                {
                                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sem mauris, consectetur nec massa eu, malesuada porta ipsum. Praesent pharetra maximus diam non maximus. Proin condimentum fermentum molestie. Aliquam convallis sed ante aliquet tristique. Mauris a nisl augue. Nulla in augue vel orci porttitor malesuada a non mauris. Proin id tincidunt lacus. Nullam sed odio dictum, semper tortor vel, finibus purus. "
                                }
                              </Trans__>
                            </div>
                          </AgendaCard>
                        </div>
                      </div>
                    </div>
                    <section
                      data-plasmic-name={"caseStudies2"}
                      data-plasmic-override={overrides.caseStudies2}
                      className={classNames(projectcss.all, sty.caseStudies2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zPxs
                        )}
                      >
                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : false
                        ) ? (
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__qzvhw)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? "292px"
                                : "274px"
                            }
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/dev_goh/images/peoplepng.png",
                              fullWidth: 1370,
                              fullHeight: 981,
                              aspectRatio: undefined
                            }}
                          />
                        ) : null}
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.columns__nEZbk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__lhnh5
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___0Saop
                              )}
                            >
                              <Trans__>
                                {
                                  <React.Fragment>
                                    <span
                                      className={
                                        "plasmic_default__all plasmic_default__span"
                                      }
                                      style={{
                                        color: "var(--token-PY84l1C8mrNw)"
                                      }}
                                    >
                                      {"How can you"}
                                    </span>
                                    <React.Fragment>{""}</React.Fragment>
                                    <span
                                      className={
                                        "plasmic_default__all plasmic_default__span"
                                      }
                                      style={{
                                        color: "var(--token-n-FzbhxKb_Pn)"
                                      }}
                                    >
                                      {" get involved? "}
                                    </span>
                                  </React.Fragment>
                                }
                              </Trans__>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___213WC
                              )}
                            >
                              <Trans__>
                                {
                                  "By joining the Connecting Climate Minds initiative, you will become a part of a growing, global and connected community, who are dedicated to creating a healthier future for both our mental well-being and the planet."
                                }
                              </Trans__>
                            </div>
                            <AntdButton
                              data-plasmic-name={"button"}
                              data-plasmic-override={overrides.button}
                              className={classNames(
                                "__wab_instance",
                                sty.button
                              )}
                              size={"large"}
                              type={"primary"}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___7VXot
                                )}
                              >
                                <Trans__>
                                  {
                                    <React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 700 }}
                                      >
                                        {"Create an Account"}
                                      </span>
                                    </React.Fragment>
                                  }
                                </Trans__>
                              </div>
                            </AntdButton>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__v6Kgy
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__tKzmn)}
                              displayHeight={"261px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"400px"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dev_goh/images/hubHowToUseTheHubV2Png.png",
                                fullWidth: 7050,
                                fullHeight: 6097,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    </section>
                  </section>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "subpageHeader",
    "agendas",
    "caseStudies",
    "toolkits",
    "caseStudies2",
    "button"
  ],
  pageLayout: [
    "pageLayout",
    "subpageHeader",
    "agendas",
    "caseStudies",
    "toolkits",
    "caseStudies2",
    "button"
  ],
  subpageHeader: ["subpageHeader"],
  agendas: ["agendas"],
  caseStudies: ["caseStudies"],
  toolkits: ["toolkits", "caseStudies2", "button"],
  caseStudies2: ["caseStudies2", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  subpageHeader: typeof SubpageHeader;
  agendas: "section";
  caseStudies: "section";
  toolkits: "section";
  caseStudies2: "section";
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicResearchAction__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicResearchAction__VariantsArgs;
    args?: PlasmicResearchAction__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicResearchAction__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicResearchAction__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicResearchAction__ArgProps,
          internalVariantPropNames: PlasmicResearchAction__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicResearchAction__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicResearchAction";
  } else {
    func.displayName = `PlasmicResearchAction.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"x1BtAZcYDoHQadMwGq1GLr"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={false}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

export const PlasmicResearchAction = Object.assign(
  // Top-level PlasmicResearchAction renders the root element
  withPlasmicPageGuard(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    subpageHeader: makeNodeComponent("subpageHeader"),
    agendas: makeNodeComponent("agendas"),
    caseStudies: makeNodeComponent("caseStudies"),
    toolkits: makeNodeComponent("toolkits"),
    caseStudies2: makeNodeComponent("caseStudies2"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicResearchAction
    internalVariantProps: PlasmicResearchAction__VariantProps,
    internalArgProps: PlasmicResearchAction__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicResearchAction;
/* prettier-ignore-end */
