// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x1BtAZcYDoHQadMwGq1GLr
// Component: 25E-dB-XJ1sI

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: aFU8osBh9vPy/component

import { useScreenVariants as useScreenVariantsxIrZdHvFaFjh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: xIrZDHvFaFjh/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x1BtAZcYDoHQadMwGq1GLr/projectcss
import sty from "./PlasmicCaseStudy.module.css"; // plasmic-import: 25E-dB-XJ1sI/css

createPlasmicElementProxy;

export type PlasmicCaseStudy__VariantMembers = {};
export type PlasmicCaseStudy__VariantsArgs = {};
type VariantPropType = keyof PlasmicCaseStudy__VariantsArgs;
export const PlasmicCaseStudy__VariantProps = new Array<VariantPropType>();

export type PlasmicCaseStudy__ArgsType = {};
type ArgPropType = keyof PlasmicCaseStudy__ArgsType;
export const PlasmicCaseStudy__ArgProps = new Array<ArgPropType>();

export type PlasmicCaseStudy__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  header?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  introduction?: Flex__<"div">;
  background?: Flex__<"div">;
  ourModel?: Flex__<"div">;
  columns?: Flex__<"div">;
  ourModel2?: Flex__<"div">;
  contact?: Flex__<"div">;
};

export interface DefaultCaseStudyProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCaseStudy__RenderFunc(props: {
  variants: PlasmicCaseStudy__VariantsArgs;
  args: PlasmicCaseStudy__ArgsType;
  overrides: PlasmicCaseStudy__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $translator = usePlasmicTranslator?.();
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxIrZdHvFaFjh()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <section
                    className={classNames(projectcss.all, sty.section__k83Ic)}
                  >
                    <div
                      data-plasmic-name={"header"}
                      data-plasmic-override={overrides.header}
                      className={classNames(projectcss.all, sty.header)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gd718
                        )}
                      >
                        <div
                          data-plasmic-name={"freeBox"}
                          data-plasmic-override={overrides.freeBox}
                          className={classNames(projectcss.all, sty.freeBox)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nAejI
                            )}
                          >
                            <Trans__>{"CASE STUDY"}</Trans__>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__t1Tx
                            )}
                          >
                            <Trans__>
                              {
                                "Enhancing access to community mental health services for women smallholder farmers affected by climate change"
                              }
                            </Trans__>
                          </div>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__opviI
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__t57Z)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"514px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/caseStudyKenyajpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1080,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                    <section
                      className={classNames(projectcss.all, sty.section__o3Wa5)}
                    >
                      <div
                        data-plasmic-name={"introduction"}
                        data-plasmic-override={overrides.introduction}
                        className={classNames(projectcss.all, sty.introduction)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zGdRy
                          )}
                        >
                          <Trans__>{"Introduction "}</Trans__>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qvRjE
                          )}
                        >
                          <Trans__>
                            {
                              <React.Fragment>
                                <React.Fragment>
                                  {
                                    "Agripsych Beam Ltd is a Kenyan Healthtech company that uses mobile technology to enhance access to mental health services to smallholder farmers affected by climate change. Our focus at AgriPsych Beam Ltd is to ensure that women smallholder farmers have a mental wellbeing safety net to fall back on after crop or livestock loss or devastation of their agriculture enterprise as a result of climate change \n\nIn many cases, climate adaption efforts mostly focus on the enterprise/business whereby the smallholder farmers are, for example, taught how to plant climate resilient crops, obtain crop insurance, or find other livelihood alternatives. Rarely do we look at the farmers and their well-being, yet for the enterprise to thrive the smallholder farmer has to be healthy. Our focus at Agripsych Beam Ltd is on the psychological well-being of the entrepreneur/ smallholder farmer.\n\nWe target women smallholder farmers who are predisposed to mental health conditions such as depression, anxiety and trauma related disorders among other mental illnesses. We combine direct farmer interactions and in some occasions engage also with organizations that work with smallholder farmers to provide various products and services to smallholder farmers such as climate smart resilient inputs.\n\nThis programme is led by Dr. Mercy Wawira Njeru who is a clinical psychologist who founded this programme when she realized that many people in communities in Kenya live through many triggers of mental health challenges and left unattended to.\n\nHer roles in the mental health field include: \n"
                                  }
                                </React.Fragment>
                                {
                                  <ul
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.ul,
                                      sty.ul___1Wy8T
                                    )}
                                  >
                                    <li
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.li,
                                        projectcss.__wab_text,
                                        sty.li__vzMnx
                                      )}
                                    >
                                      {
                                        "Creating community mental health programmes through Agripsych Beam Ltd and Psychwell Essence\nFoundation that provide access to affordable or free mental health services to women smallholder farmers that\nare affected by climate change and the low-income rural communities."
                                      }
                                    </li>
                                    <li
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.li,
                                        projectcss.__wab_text,
                                        sty.li___8Re74
                                      )}
                                    >
                                      {
                                        "Running of a mental health private clinic in Westlands area of Nairobi, Kenya.  "
                                      }
                                    </li>
                                  </ul>
                                }
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <ul
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.ul,
                                      sty.ul___5BHsc
                                    )}
                                  >
                                    <li
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.li,
                                        projectcss.__wab_text,
                                        sty.li__bJfYf
                                      )}
                                    >
                                      {
                                        "Treatment of inpatients and outpatients in Oasis Mental Health Specialty Hospital where she is also in the hospital governance committee and Chiromo Hospital GroupS"
                                      }
                                    </li>
                                  </ul>
                                }
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <ul
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.ul,
                                      sty.ul__pwGsF
                                    )}
                                  >
                                    <li
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.li,
                                        projectcss.__wab_text,
                                        sty.li__geeo6
                                      )}
                                    >
                                      {"Mentoring of young psychologistsS"}
                                    </li>
                                  </ul>
                                }
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <ul
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.ul,
                                      sty.ul__hNpT
                                    )}
                                  >
                                    <li
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.li,
                                        projectcss.__wab_text,
                                        sty.li__k29Gn
                                      )}
                                    >
                                      {
                                        "Has published \u201cThe Effects of Climate Change on the Mental Health of Smallholder Crop Farmers in Embu and\nMeru Counties of Kenya\u201d and \u201cThe Coping Mechanisms Utilized by Smallholder Crop Farmers to Cope with the Effects of Climate Change and Mental Illnesses in Embu and Meru Counties of Kenya (Pers.Comm)\u201d."
                                      }
                                    </li>
                                  </ul>
                                }
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            }
                          </Trans__>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ecobY
                          )}
                        >
                          <Trans__>{"\n\n"}</Trans__>
                        </div>
                      </div>
                    </section>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__wxpbf)}
                  >
                    <div
                      data-plasmic-name={"background"}
                      data-plasmic-override={overrides.background}
                      className={classNames(projectcss.all, sty.background)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__raPUn
                        )}
                      >
                        <Trans__>{"Background"}</Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1UUad
                        )}
                      >
                        <Trans__>
                          {
                            "Food Security for Mental Health and the Impacts of Climate Change"
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zwOlp
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "Induced stress due to climate change causes anxiety, depression, trauma, aggression, antisocial behavior, dissociation & substance use (APA, 2021).\n\nYazd et al. (2019) state farming is a stressful occupation; climate change makes it worse. More than 80% of food in the world is produced by smallholder farmers who do not have access to mental health services.\n\nKenya experiences widespread and visible climate change impacts, which is impacting ; farmer\u2019s mental health. A study in Eastern Kenya on smallholder farmers indicate a prevalence rate of 35.2% mental health issues, 67% of the study participants were women farmers (Njeru, 2022).\n\n"
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {"Climate Change Problems Reported:"}
                              </span>
                              <React.Fragment>
                                {
                                  "\n\nThe women smallholder farmers from our firsthand conversations state that climate change has affected them negatively in terms of livelihood. Problems reported include:\n\nDried up rivers due to climate change that leaves them with no water for their livestock and farming.\n"
                                }
                              </React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__mg3DQ
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__zJCil
                                    )}
                                  >
                                    {
                                      "Death of livestock from impact of climate change (no water and too much heat hence no fodder or grazing). "
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__dgngF
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__axmaN
                                    )}
                                  >
                                    {
                                      "Reduced agricultural crop productivity due to little or no rains, which causes drought."
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__eElyl
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__qIuI
                                    )}
                                  >
                                    {
                                      "Occasional migration to look for other regions that the smallholder farmers can farm crops or graze the animals."
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__ijNzX
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__b5CaP
                                    )}
                                  >
                                    {
                                      "Increased familial distress as a result of the stresses associated with climate change because families are\nless happy and hence fight a lot."
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__i0184
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__o6XDl
                                    )}
                                  >
                                    {
                                      "Financial distress because these smallholder farmers cannot sell any crop or livestock if this was their economic activity. The little they harvest is all consumed at home."
                                    }
                                  </li>
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__fNmPd
                                    )}
                                  >
                                    {
                                      "Shifts to alternative economic activities such as cutting down the few trees left to sell charcoal for income. This in turn increases climate change and makes their situation worse.\u0016"
                                    }
                                  </li>
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__fi69S
                                    )}
                                  >
                                    {
                                      "Children dropping out of school because there is no income to pay their school fees or it is too hot to go to school or are now required at home to go look for water in far places that take hours."
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{"\n"}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {
                                  "Mental Health Issues as a Result of Climate Change:"
                                }
                              </span>
                              <React.Fragment>
                                {
                                  "\n\nOur women smallholder farmers report that their physical and psychological health has been negatively affected by climate changes. Problems reported include:\n\n"
                                }
                              </React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__vbvK
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__co1Bt
                                    )}
                                  >
                                    {
                                      "Severe climate anxiety related disorders whereby the smallholder farmers are always anxious and have intense worry every season on whether there will be rain for their crops to grow or to fill up the rivers and water tanks.\u0016"
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__myhLp
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__i1A6Q
                                    )}
                                  >
                                    {
                                      "Cases of depression related disorders as these farmers experience hopelessness, insomnia and even suicidal thoughts due to the sad state of affairs caused by climate change.\u0016"
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__dxNnM
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__b6Co7
                                    )}
                                  >
                                    {
                                      "Trauma related disorders that are caused by the constant moving as they lose their current livelihood as well as sometimes lose their loved ones due to droughts.\u0016"
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__voje9
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li___2VI0G
                                    )}
                                  >
                                    {
                                      "Some families report psychosis occasioned by intense psychosocial stressors such as loss of all their cattle/ goats due to dried up rivers and no grass available to feed their livestock.\u0016"
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__irOHf
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__vVHd
                                    )}
                                  >
                                    {
                                      "Broken homes as families are not able to cope with the effects of climate change in a healthy way hence end up fighting a lot or homes end up broken.\u0016"
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__kU7Gn
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li___5Pxjf
                                    )}
                                  >
                                    {
                                      "Multiplier effects of climate change such as no rain causing loss of crops/ death livestock lead to no income which means no school for their children and hence this cause mental health problems such as anxiety, depression and a generation that does not get education.\u0016"
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__nsgK
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__iW2RS
                                    )}
                                  >
                                    {
                                      "Cases of medical conditions such as diabetes due to poor eating habits or malnutrition, hypertension, infectious diseases among others that add to their already heavy burden of climate change and mental health issues."
                                    }
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"ourModel"}
                      data-plasmic-override={overrides.ourModel}
                      className={classNames(projectcss.all, sty.ourModel)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sqrZ
                        )}
                      >
                        <Trans__>{"Our model"}</Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iueO
                        )}
                      >
                        <Trans__>
                          {
                            "The current ratio of mental health practitioner to patient in Sub-Saharan Africa 1.4 mental health workers per 100,000 people. African countries have not been able to navigate effectively the mental health of their communities.\n\nWHO estimates Kenya allocates about 0.05% of its health budget to mental health centralizing about 70% of these resources to its capital city, Nairobi, leaving few services for rural low-income communities.\n\nThis is an indication that these rural communities where smallholder farmers fall in are left exposed without access to affordable mental healthcare.\n\nThe above led to Agripsych Beam Limited creating mental health solutions for these smallholder farmers since 2020 to date.\nThe goal has consistently been to provide access to affordable or free mental healthcare services to women smallholder farmers. Below are examples of activities we engage in:"
                          }
                        </Trans__>
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ak7Ai)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/dev_goh/images/screenshot20240214At124535Pmpng.png",
                          fullWidth: 1896,
                          fullHeight: 812,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        data-plasmic-name={"columns"}
                        data-plasmic-override={overrides.columns}
                        className={classNames(projectcss.all, sty.columns)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__kQbjk
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__dZ6H)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/dev_goh/images/screenshot20240214At124551Pmpng.png",
                              fullWidth: 1902,
                              fullHeight: 1070,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__sFr
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___6U6W)}
                            displayHeight={
                              hasVariant(globalVariants, "screen", "mobileOnly")
                                ? "213px"
                                : "306px"
                            }
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/dev_goh/images/screenshot20240214At124605Pmpng.png",
                              fullWidth: 1898,
                              fullHeight: 1212,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                    </div>
                  </section>
                  <div
                    data-plasmic-name={"ourModel2"}
                    data-plasmic-override={overrides.ourModel2}
                    className={classNames(projectcss.all, sty.ourModel2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jhwu
                      )}
                    >
                      <Trans__>
                        {
                          "Food Security for Mental Health and the Impacts of Climate Change"
                        }
                      </Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lK6P
                      )}
                    >
                      <Trans__>{"Individual and Group Therapy"}</Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dEvr2
                      )}
                    >
                      <Trans__>
                        {
                          "We have been doing individual and group therapy with women smallholder farmers to help them in dealing with the mental health challenges caused by climate change."
                        }
                      </Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wtouw
                      )}
                    >
                      <Trans__>{"Pre-recorded therapy calls"}</Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ehkuR
                      )}
                    >
                      <Trans__>
                        {
                          "We have collaborated with a local telecommunication company to send out pre-recorded and prepaid therapy calls to smallholder farmers every week. Our goal is to make affordable/ free mental health services accessible to smallholder farmers. We plan in the coming years is to reach millions of smallholder farmers in Kenya with this service."
                        }
                      </Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pquQn
                      )}
                    >
                      <Trans__>{"Training of para therapists"}</Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jPk3O
                      )}
                    >
                      <Trans__>
                        {
                          "Para therapists/ Community based therapists are the first people to interact with the smallholder farmers in the rural areas at Embu Community we therefore have been training and psychoeducating community health champions on identification of mental health issues for appropriate referral and management."
                        }
                      </Trans__>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"contact"}
                    data-plasmic-override={overrides.contact}
                    className={classNames(projectcss.all, sty.contact)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ycb8T
                      )}
                    >
                      <Trans__>{"Contact"}</Trans__>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fNfgs
                      )}
                    >
                      <Trans__>
                        {
                          <React.Fragment>
                            <React.Fragment>{"Email Address: "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"mercy@agripsychbeam.com"}
                            </span>
                            <React.Fragment>{"\n\nTelephone: "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"+ 254 700 513 580"}
                            </span>
                            <React.Fragment>{"\n\nAddress: "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Mwanzi Road Westlands, Nairobi, Kenya"}
                            </span>
                          </React.Fragment>
                        }
                      </Trans__>
                    </div>
                  </div>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "header",
    "freeBox",
    "introduction",
    "background",
    "ourModel",
    "columns",
    "ourModel2",
    "contact"
  ],
  pageLayout: [
    "pageLayout",
    "header",
    "freeBox",
    "introduction",
    "background",
    "ourModel",
    "columns",
    "ourModel2",
    "contact"
  ],
  header: ["header", "freeBox"],
  freeBox: ["freeBox"],
  introduction: ["introduction"],
  background: ["background"],
  ourModel: ["ourModel", "columns"],
  columns: ["columns"],
  ourModel2: ["ourModel2"],
  contact: ["contact"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  header: "div";
  freeBox: "div";
  introduction: "div";
  background: "div";
  ourModel: "div";
  columns: "div";
  ourModel2: "div";
  contact: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCaseStudy__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCaseStudy__VariantsArgs;
    args?: PlasmicCaseStudy__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCaseStudy__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCaseStudy__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCaseStudy__ArgProps,
          internalVariantPropNames: PlasmicCaseStudy__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCaseStudy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCaseStudy";
  } else {
    func.displayName = `PlasmicCaseStudy.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"x1BtAZcYDoHQadMwGq1GLr"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={false}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

export const PlasmicCaseStudy = Object.assign(
  // Top-level PlasmicCaseStudy renders the root element
  withPlasmicPageGuard(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    header: makeNodeComponent("header"),
    freeBox: makeNodeComponent("freeBox"),
    introduction: makeNodeComponent("introduction"),
    background: makeNodeComponent("background"),
    ourModel: makeNodeComponent("ourModel"),
    columns: makeNodeComponent("columns"),
    ourModel2: makeNodeComponent("ourModel2"),
    contact: makeNodeComponent("contact"),

    // Metadata about props expected for PlasmicCaseStudy
    internalVariantProps: PlasmicCaseStudy__VariantProps,
    internalArgProps: PlasmicCaseStudy__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCaseStudy;
/* prettier-ignore-end */
