// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x1BtAZcYDoHQadMwGq1GLr
// Component: rKCP9GG2UqSk

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageLayout from "../../PageLayout"; // plasmic-import: aFU8osBh9vPy/component
import SubpageHeader from "../../SubpageHeader"; // plasmic-import: lpLjDJwsHcxv/component
import InfoModuleRight from "../../InfoModuleRight"; // plasmic-import: Y3yqKabe7t4u/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import NewsCardRow from "../../NewsCardRow"; // plasmic-import: 5AhTJka5kXTV/component
import RegionalTeam from "../../RegionalTeam"; // plasmic-import: noYhTenpbxJe/component

import { useScreenVariants as useScreenVariantsxIrZdHvFaFjh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: xIrZDHvFaFjh/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x1BtAZcYDoHQadMwGq1GLr/projectcss
import sty from "./PlasmicRegionalCommunity.module.css"; // plasmic-import: rKCP9GG2UqSk/css

createPlasmicElementProxy;

export type PlasmicRegionalCommunity__VariantMembers = {};
export type PlasmicRegionalCommunity__VariantsArgs = {};
type VariantPropType = keyof PlasmicRegionalCommunity__VariantsArgs;
export const PlasmicRegionalCommunity__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRegionalCommunity__ArgsType = {};
type ArgPropType = keyof PlasmicRegionalCommunity__ArgsType;
export const PlasmicRegionalCommunity__ArgProps = new Array<ArgPropType>();

export type PlasmicRegionalCommunity__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  subpageHeader?: Flex__<typeof SubpageHeader>;
  infoModuleRight?: Flex__<typeof InfoModuleRight>;
  regionalAgenda?: Flex__<"div">;
  button?: Flex__<typeof AntdButton>;
  regionalCaseStudies?: Flex__<"div">;
  regionalNews?: Flex__<"div">;
  regionalTeam?: Flex__<typeof RegionalTeam>;
};

export interface DefaultRegionalCommunityProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRegionalCommunity__RenderFunc(props: {
  variants: PlasmicRegionalCommunity__VariantsArgs;
  args: PlasmicRegionalCommunity__ArgsType;
  overrides: PlasmicRegionalCommunity__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $translator = usePlasmicTranslator?.();
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxIrZdHvFaFjh()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <SubpageHeader
                    data-plasmic-name={"subpageHeader"}
                    data-plasmic-override={overrides.subpageHeader}
                    className={classNames("__wab_instance", sty.subpageHeader)}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hgzU1
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>
                                {
                                  "This is a connected, supported and engaged space that brings together the latest Connecting Climate Minds project "
                                }
                              </React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 500 }}
                              >
                                {"outputs, events, news, resources and people"}
                              </span>
                              <React.Fragment>
                                {
                                  " working in climate change and mental health in the region. "
                                }
                              </React.Fragment>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                    }
                    slot2={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___4Yv80)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"429px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/dev_goh/images/subSaharanAfricaRCjpg.jpg",
                          fullWidth: 1920,
                          fullHeight: 1080,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pNv8S
                      )}
                    >
                      <Trans__>
                        {
                          <React.Fragment>
                            <React.Fragment>{"Welcome to the "}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                            >
                              {"Sub-Saharan Africa "}
                            </span>
                            <React.Fragment>
                              {"regional community of practice "}
                            </React.Fragment>
                          </React.Fragment>
                        }
                      </Trans__>
                    </div>
                  </SubpageHeader>
                  <InfoModuleRight
                    data-plasmic-name={"infoModuleRight"}
                    data-plasmic-override={overrides.infoModuleRight}
                    className={classNames(
                      "__wab_instance",
                      sty.infoModuleRight
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yj4ZQ
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__sZs60
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__v2IoY
                                    )}
                                  >
                                    <React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 500 }}
                                      >
                                        {
                                          "Stay up to date with the latest climate change and mental health resources in Sub-Saharan Africa."
                                        }
                                      </span>
                                      <React.Fragment>{"\n"}</React.Fragment>
                                    </React.Fragment>
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{"\n"}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__sH1Yj
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__yiTzi
                                    )}
                                  >
                                    <React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 500 }}
                                      >
                                        {
                                          "Connect with other people across disciplines, sectors and countries interested in changing the landscape of climate change and mental health research and policy"
                                        }
                                      </span>
                                      <React.Fragment>{"\n"}</React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 500 }}
                                      >
                                        {"."}
                                      </span>
                                      <React.Fragment>{"\n"}</React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 500 }}
                                      >
                                        {""}
                                      </span>
                                    </React.Fragment>
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <ul
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.ul,
                                    sty.ul__alVEy
                                  )}
                                >
                                  <li
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.li,
                                      projectcss.__wab_text,
                                      sty.li__iv0Vq
                                    )}
                                  >
                                    <React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ fontWeight: 500 }}
                                      >
                                        {
                                          "Find opportunities to get involved: whether you are a researcher, policymaker, health professional, teacher, community organiser - your skills and expertise are needed."
                                        }
                                      </span>
                                    </React.Fragment>
                                  </li>
                                </ul>
                              }
                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iyRlw
                        )}
                      >
                        <Trans__>{"Join Community"}</Trans__>
                      </div>
                    }
                    slot3={
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___99Kjo)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "275px"
                            : "316px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "403px"
                            : "428px"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/dev_goh/images/ssaBenefitspng3.png",
                          fullWidth: 2192,
                          fullHeight: 2129,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eWxea
                      )}
                    >
                      <Trans__>
                        {
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-qrT8uUlt7cMG)" }}
                            >
                              {"Why join our regional community? "}
                            </span>
                          </React.Fragment>
                        }
                      </Trans__>
                    </div>
                  </InfoModuleRight>
                  <section
                    className={classNames(projectcss.all, sty.section__by8N)}
                  >
                    <div
                      data-plasmic-name={"regionalAgenda"}
                      data-plasmic-override={overrides.regionalAgenda}
                      className={classNames(projectcss.all, sty.regionalAgenda)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__wfgyr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__feqS4
                          )}
                        >
                          <Trans__>
                            {
                              <React.Fragment>
                                <span
                                  className={
                                    "plasmic_default__all plasmic_default__span"
                                  }
                                  style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                                >
                                  {"Sub-Saharan Africa"}
                                </span>
                                <React.Fragment>
                                  {" research and action agenda"}
                                </React.Fragment>
                              </React.Fragment>
                            }
                          </Trans__>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6MbQg
                          )}
                        >
                          <Trans__>
                            {
                              "An ambitious and inclusive agenda setting out research priorities within the region, and actions enable this research and translate evidence into action in policy and practice. This will act as a guide for the field, supporting creation of the evidence needed for policy and practice to safeguard mental health while enabling climate action, deeply grounded in the needs of people with lived experience."
                            }
                          </Trans__>
                        </div>
                        <AntdButton
                          data-plasmic-name={"button"}
                          data-plasmic-override={overrides.button}
                          className={classNames("__wab_instance", sty.button)}
                          shape={"default"}
                          size={"large"}
                          type={"primary"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gVe0X
                            )}
                          >
                            <Trans__>{"View Regional Agenda"}</Trans__>
                          </div>
                        </AntdButton>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__fsc2B
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__ronz2)}
                          displayHeight={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "295px"
                              : "auto"
                          }
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"383px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/ssaAgendapng2.png",
                            fullWidth: 1994,
                            fullHeight: 1801,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </section>
                  <div
                    data-plasmic-name={"regionalCaseStudies"}
                    data-plasmic-override={overrides.regionalCaseStudies}
                    className={classNames(
                      projectcss.all,
                      sty.regionalCaseStudies
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__hNpj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uOaRf
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-PY84l1C8mrNw)" }}
                              >
                                {"Successful "}
                              </span>
                              <React.Fragment>{""}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                              >
                                {"case studies"}
                              </span>
                              <React.Fragment>{""}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-PY84l1C8mrNw)" }}
                              >
                                {" across the region"}
                              </span>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gCTt
                        )}
                      >
                        <Trans__>
                          {
                            "Explore our collection of case studies and projects in  Sub-Saharan Africa that celebrate the progress being made on the ground to respond to the mental health impacts of climate change.  "
                          }
                        </Trans__>
                      </div>
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qogoz)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "auto"
                            : "579px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "100%"
                            : "100%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/dev_goh/images/caseStudyMapSsAjpg.jpg",
                          fullWidth: 3840,
                          fullHeight: 2160,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                  <section
                    className={classNames(projectcss.all, sty.section__srlTn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__azLMd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vzUpl
                        )}
                      >
                        <Trans__>
                          {
                            "Tapestry of individual and collective lived experience insights "
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___20R8Z
                        )}
                      >
                        <Trans__>
                          {
                            "Browse our collection of videos and audio clips bringing to life the lived experience of people across  Sub-Saharan Africa experiencing and responding to the mental health impacts of climate change. \n"
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__ovRf4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__tvOU
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__j2IxC)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/dev_goh/images/screenshot20240207At34011Pmpng.png",
                              fullWidth: 1674,
                              fullHeight: 622,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                    </div>
                  </section>
                  <div
                    data-plasmic-name={"regionalNews"}
                    data-plasmic-override={overrides.regionalNews}
                    className={classNames(projectcss.all, sty.regionalNews)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__sGaO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__am3C
                        )}
                      >
                        <Trans__>
                          {
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-n-FzbhxKb_Pn)" }}
                              >
                                {"Sub-Saharan Africa"}
                              </span>
                              <React.Fragment>
                                {" regional news"}
                              </React.Fragment>
                            </React.Fragment>
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ehbGb
                        )}
                      >
                        <Trans__>
                          {
                            "Read the latest news in climate change and mental health research and policy for the region."
                          }
                        </Trans__>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__vzPdb
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__f9Tg
                          )}
                        >
                          <NewsCardRow
                            className={classNames(
                              "__wab_instance",
                              sty.newsCardRow__fTvJ
                            )}
                            slot={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___2WEue
                                )}
                              >
                                <Trans__>
                                  {
                                    "South African State Climate Body Slams National Energy Plan"
                                  }
                                </Trans__>
                              </div>
                            }
                            slot2={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vmNvN
                                )}
                              >
                                <Trans__>
                                  {
                                    "Cras purus ex, dictum a odio sed, euismod semper risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
                                  }
                                </Trans__>
                              </div>
                            }
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__xXgqq)}
                              displayHeight={"100%"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dev_goh/images/news1Png.png",
                                fullWidth: 3840,
                                fullHeight: 2160,
                                aspectRatio: undefined
                              }}
                            />
                          </NewsCardRow>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__mZk3Z
                          )}
                        >
                          <NewsCardRow
                            className={classNames(
                              "__wab_instance",
                              sty.newsCardRow__qPn3Z
                            )}
                            slot={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__rl8FW
                                )}
                              >
                                <Trans__>
                                  {
                                    "What is Africa\u2019s goal at COP28 as the climate summit begins?"
                                  }
                                </Trans__>
                              </div>
                            }
                            slot2={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__hDcAs
                                )}
                              >
                                <Trans__>
                                  {
                                    "Cras purus ex, dictum a odio sed, euismod semper risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
                                  }
                                </Trans__>
                              </div>
                            }
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__hXvuc)}
                              displayHeight={"100%"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dev_goh/images/news2Png.png",
                                fullWidth: 3840,
                                fullHeight: 2160,
                                aspectRatio: undefined
                              }}
                            />
                          </NewsCardRow>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__oNgPr
                          )}
                        >
                          <NewsCardRow
                            className={classNames(
                              "__wab_instance",
                              sty.newsCardRow___2UaRr
                            )}
                            slot={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__b2Asc
                                )}
                              >
                                <Trans__>
                                  {
                                    "Catalyst Fund Invests $1.8 Million in Nine African Climate Startups"
                                  }
                                </Trans__>
                              </div>
                            }
                            slot2={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__nPsq8
                                )}
                              >
                                <Trans__>
                                  {
                                    "Cras purus ex, dictum a odio sed, euismod semper risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
                                  }
                                </Trans__>
                              </div>
                            }
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__fKubk)}
                              displayHeight={"100%"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dev_goh/images/news3Png.png",
                                fullWidth: 3840,
                                fullHeight: 2160,
                                aspectRatio: undefined
                              }}
                            />
                          </NewsCardRow>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__zanD
                          )}
                        >
                          <NewsCardRow
                            className={classNames(
                              "__wab_instance",
                              sty.newsCardRow__reUb
                            )}
                            slot={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__jecom
                                )}
                              >
                                <Trans__>
                                  {
                                    "Africa and India push rich nations to phase out fossil fuels faster"
                                  }
                                </Trans__>
                              </div>
                            }
                            slot2={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__snzL
                                )}
                              >
                                <Trans__>
                                  {
                                    "Cras purus ex, dictum a odio sed, euismod semper risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
                                  }
                                </Trans__>
                              </div>
                            }
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__nVf0B)}
                              displayHeight={"100%"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/dev_goh/images/news4Png.png",
                                fullWidth: 3840,
                                fullHeight: 2160,
                                aspectRatio: undefined
                              }}
                            />
                          </NewsCardRow>
                        </div>
                      </div>
                    </div>
                  </div>
                  <RegionalTeam
                    data-plasmic-name={"regionalTeam"}
                    data-plasmic-override={overrides.regionalTeam}
                    className={classNames("__wab_instance", sty.regionalTeam)}
                  />

                  <section
                    className={classNames(projectcss.all, sty.section__sUoQd)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uT0QK)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___912Xh
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___5XkA2)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/logo1Png.png",
                            fullWidth: 1054,
                            fullHeight: 772,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fi8Du
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__exssT)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/logo2Png.png",
                            fullWidth: 1054,
                            fullHeight: 772,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qFcSh
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__nlmye)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/logo3Png.png",
                            fullWidth: 1054,
                            fullHeight: 772,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nnohM
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__jXrx4)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/logo4Png.png",
                            fullWidth: 1054,
                            fullHeight: 772,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qtrbx
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__zR4Gn)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/dev_goh/images/logo5Png.png",
                            fullWidth: 1054,
                            fullHeight: 772,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </section>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "subpageHeader",
    "infoModuleRight",
    "regionalAgenda",
    "button",
    "regionalCaseStudies",
    "regionalNews",
    "regionalTeam"
  ],
  pageLayout: [
    "pageLayout",
    "subpageHeader",
    "infoModuleRight",
    "regionalAgenda",
    "button",
    "regionalCaseStudies",
    "regionalNews",
    "regionalTeam"
  ],
  subpageHeader: ["subpageHeader"],
  infoModuleRight: ["infoModuleRight"],
  regionalAgenda: ["regionalAgenda", "button"],
  button: ["button"],
  regionalCaseStudies: ["regionalCaseStudies"],
  regionalNews: ["regionalNews"],
  regionalTeam: ["regionalTeam"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  subpageHeader: typeof SubpageHeader;
  infoModuleRight: typeof InfoModuleRight;
  regionalAgenda: "div";
  button: typeof AntdButton;
  regionalCaseStudies: "div";
  regionalNews: "div";
  regionalTeam: typeof RegionalTeam;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRegionalCommunity__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRegionalCommunity__VariantsArgs;
    args?: PlasmicRegionalCommunity__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRegionalCommunity__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRegionalCommunity__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRegionalCommunity__ArgProps,
          internalVariantPropNames: PlasmicRegionalCommunity__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRegionalCommunity__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRegionalCommunity";
  } else {
    func.displayName = `PlasmicRegionalCommunity.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"x1BtAZcYDoHQadMwGq1GLr"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={false}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

export const PlasmicRegionalCommunity = Object.assign(
  // Top-level PlasmicRegionalCommunity renders the root element
  withPlasmicPageGuard(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    subpageHeader: makeNodeComponent("subpageHeader"),
    infoModuleRight: makeNodeComponent("infoModuleRight"),
    regionalAgenda: makeNodeComponent("regionalAgenda"),
    button: makeNodeComponent("button"),
    regionalCaseStudies: makeNodeComponent("regionalCaseStudies"),
    regionalNews: makeNodeComponent("regionalNews"),
    regionalTeam: makeNodeComponent("regionalTeam"),

    // Metadata about props expected for PlasmicRegionalCommunity
    internalVariantProps: PlasmicRegionalCommunity__VariantProps,
    internalArgProps: PlasmicRegionalCommunity__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRegionalCommunity;
/* prettier-ignore-end */
