// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicNewsModule,
  DefaultNewsModuleProps
} from "./plasmic/dev_goh/PlasmicNewsModule";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface NewsModuleProps extends Omit<DefaultNewsModuleProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultNewsModuleProps altogether and have
// total control over the props for your component.
export interface NewsModuleProps extends DefaultNewsModuleProps {}

function NewsModule_(props: NewsModuleProps, ref: HTMLElementRefOf<"section">) {
  // Use PlasmicNewsModule to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicNewsModule are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all NewsModuleProps here, but feel free
  // to do whatever works for you.

  return <PlasmicNewsModule news={{ ref }} {...props} />;
}

const NewsModule = React.forwardRef(NewsModule_);
export default NewsModule;
